config/routes.rb
Rails.application.routes.draw do
  
  resources :spaces
  
  resources :spaces do
	  resources :bookings
	end

  devise_for :users
  

  
  
  
  get 'static_pages/about'
  
  get 'static_pages/contact'

  root 'static_page#about'

end

app/models/booking.rb
require_relative './concerns/bookable'

class Booking < ActiveRecord::Base
  include Bookable
  
  belongs_to :space
end

app/models/concerns/bookable.rb
module Bookable
  extend ActiveSupport::Concern

  included do
    belongs_to :space

    validates :start_time, presence: true 
    validates :length, presence: true, numericality: { greater_than: 0 }
    validate :start_date_cannot_be_in_the_past
    validate :overlaps

    before_validation :calculate_end_time
  

    scope :end_during, ->(new_start_time, new_end_time) do
      if (!new_start_time.nil?) && (!new_end_time.nil?)
        where('end_time > ? AND end_time < ?', new_start_time, new_end_time)
      else
        return nil
      end
    end

    scope :start_during, ->(new_start_time, new_end_time) do
      if (!new_start_time.nil?) && (!new_end_time.nil?)
        where('start_time > ? AND start_time < ?', new_start_time, new_end_time)
      else
        return nil
      end
    end

    scope :happening_during, ->(new_start_time, new_end_time) do
      if (!new_start_time.nil?) && (!new_end_time.nil?)
        where('start_time > ? AND end_time < ?', new_start_time, new_end_time)
      else
        return nil
      end 
    end

    scope :enveloping, ->(new_start_time, new_end_time) do
      if (!new_start_time.nil?) && (!new_end_time.nil?)
        where('start_time < ? AND end_time > ?', new_start_time, new_end_time)
      else
        return nil
      end
    end

    scope :identical, ->(new_start_time, new_end_time) do
      if (!new_start_time.nil?) && (!new_end_time.nil?)
        where('start_time = ? AND end_time = ?', new_start_time, new_end_time)
      else
        return nil
      end
    end
  end

  def overlaps
    overlapping_bookings = [ 
      space.bookings.end_during(start_time, end_time),
      space.bookings.start_during(start_time, end_time),
      space.bookings.happening_during(start_time, end_time),
      space.bookings.enveloping(start_time, end_time),
      space.bookings.identical(start_time, end_time)
    ].flatten

    overlapping_bookings.delete self
    if overlapping_bookings.any?
      errors.add(:base, 'Slot has already been booked')
    end
  end

  def start_date_cannot_be_in_the_past
    if start_time && start_time < DateTime.now + (15.minutes)
      errors.add(:start_time, 'must be at least 15 minutes from present time')
    end
  end

  def calculate_end_time
    start_time = validate_start_time
    length = validate_length
    if start_time && length
      self.end_time = start_time + (length.hours - 60)
    end
  end


  def as_json(options = {})  
   {  
    :id => self.id,  
    :start => self.start_time,  
    :end => self.end_time + 60,  
    :recurring => false, 
    :allDay => false
   }  
  end  

  private

    def validate_start_time
      if !self.start_time.nil?
        start_time = self.start_time
      else
        return nil
      end
    end

    def validate_length
      if !self.length.nil?
        length = self.length.to_i
      else
        return nil
      end
    end

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :spaces

end

app/models/resource.rb
class Resource < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :bookings
end

app/models/space.rb
class Space < ActiveRecord::Base
  
  mount_uploader :image, ImageUploader
  
  has_many :users, through: :bookings
  has_many :bookings
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
 
  has_many :bookings
  has_many :spaces, through: :bookings
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
    @space = Space.find(params[:space_id])
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
    
    @space = Space.find(params[:space_id])
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    
    @booking = Booking.new(booking_params)
    @space = Space.find(params[:space_id])
    @booking.space_id = @space.id
    @booking.user_id = current_user.id

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @space, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:start, :end, :user_id, :space_id, :start_time, :end_time, :length)
    end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  #before_filter :check_user, only: [:edit, :update, :destroy]

  
  def show
    @space = Space.find(params[:id])  
  end
  
  def index
    @spaces = Space.all
  end

  def new
    @space = Space.new
  end

  def create
    @space = Space.new(space_params)
    @space.user_id = current_user.id
   respond_to do |format| 
    if @space.save
      format.html { redirect_to @space, notice: 'Space was successfully updated.' }
      format.json { render :show, status: :ok, location: @space }
      else
        format.html { render :edit }
      format.json { render json: @space.errors, status: :unprocessable_entity }
    end
    end
  end

  def destroy
    @space = Space.find(params[:id])
    @space.destroy
    redirect_to spaces_path
  end

  def edit
    @space = Space.find(params[:id])
  end

  def update
    respond_to do |format|
      if @space.update(space_params)
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { render :show, status: :ok, location: @space}
      else
        format.html { render :edit }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def set_space
    @space = Space.find(params[:id])
    end
  

    def space_params
      params.require(:space).permit(:name, :address, :description, :city, :state, :zip, :price, :number_of_seats, :user_id, :image)
    end
  
#def check_user
  #if current_user != @space.user
 #   redirect_to root_url, alert: "Sorry, this Space belongs to someone else"\
  #    end
 # end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  
  def contact
  end
  
  def about
    @spaces=Space.take(3)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/bookings/_errors.html.erb
<% if @booking.errors.any? %>
  <div class="errors">
    <h3><%= pluralize(@booking.errors.count, 'error') %>
      prohibited this booking from being saved:
    </h3>
    <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/bookings/_form.html.erb
<%= form_for([@space, @booking]) do |f| %>
<section>
<div class="container">
<div class="booking-section mrgb7x">
<div class="row">
	<div class="col-md-4 col-md-offset-2 col-sm-6 animated out" data-delay="0" data-animation="fadeInUp">
		<div class="booking-title"> <span>1</span>
			<h4>property information</h4>
		</div>
		<div class="property-info mrgt6x">
			<div class="property-box border-hover">
        <div class="appartment-img"><%= cl_image_tag(@space.image_url(:thumbnail)) %>
          <div class="room-price"><span><%= @space.price %><sup>/week</sup></span></div>
					<div class="like-btn"><a href="#"><i class="fa fa-heart"></i></a></div>
				</div>
				<div class="property-text">
					<div class="resort-name">
            <h4><%= @space.name %></h4>
						<div class="rating"> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> </div>
            <p><%= @space.city %>, <%= @space.state %> </p>
					</div>
				</div>
				
			</div>
		</div>
	</div>
	<div class="col-md-4 col-sm-6 animated out" data-delay="0" data-animation="fadeInUp">
		<div class="booking-title"> <span>3</span>
			<h4>Time Selection</h4>
		</div>
		<div class="payment-method mrgt6x">
			<form id="payment-form" method="post" name="payment">
			
				<div class="form-group">
					<label>Start time</label><br>
          <%= f.datetime_select :start_time, { minute_step: 15 } %>
				</div>
				<div class="form-group">
					<label>Duration of Booking (in hours)</label>
					<%= f.number_field 'length', min: 1 , class:"form-control" %>
				</div>
				<div class="col-md-6 no-padding">
          <%= f.submit 'Book this Space!', class:"btn btn-primary btn-lg" %>
				</div>
				<div class="col-md-6 padding-rit0">

				</div>
			</form>
		</div>
	</div>
	</div>
	</div>
</div>
</section>

<% end %> 

app/views/bookings/edit.html.erb
<h3>Edit booking for <%= @space.name %></h3>

<%= render 'errors' %>
<%= render 'form' %>

<div class="calendar_container">
  <div id="calendar">
  </div>
</div>

app/views/bookings/index.html.erb
<h3> Bookings for <%= @space.name %></h3>
<table class="bookings_table">
  <tr>
    <th>Start</th>
    <th>End</th>
  </tr>
  
  <% @bookings.each do |booking| %>
  <tr>
    <td>
      <%= booking.start_time.strftime('%e %b %Y %H:%M%p') %>
    </td>
    <td>
      <%= (booking.calculate_end_time + 60).strftime('%e %b %Y %H:%M%p') %>
    </td>
    <td><%= link_to "Delete", space_booking_path(@space, booking), data: { confirm: 'Are you sure?' }, method: :delete %>
    </td>
    <td><%= link_to "Edit", edit_space_booking_path(@space, booking) %>
    </td>
  </tr>
  <% end %>
</table>

app/views/bookings/new.html.erb
<h3>Add booking for <%= @space.name %></h3>
  
<%= render 'errors' %>
<%= render 'form' %> 

<div class="calendar_container">
  <div id="calendar">
  </div>
</div>

app/views/bookings/show.html.erb
<h3>Booking Confirmation</h3>
<p>Your booking is confirmed for
  <%= @space.name %>:
  <%= @booking.start_time.strftime('%e %b %Y %H:%M%p') %>
  until
  <%= (@booking.calculate_end_time + 60).strftime('%e %b %Y %H:%M%p') %>

app/views/layouts/_footer.html.erb
<footer class="bg-color">
	<div class="container">
		<div class="upper-footer clearfix">
			<div class="widgets">
				<div class="col-md-3">
					<div class="about-widget"> 
						<p>Alternatively if you have a specific service or question in mind please don’t hesitate to contact us to discuss this using the contact details on the Contact Us page of the site.</p>
					</div>
				</div>
				<div class="col-md-3">
					<div class="widget-heading mrgb4x">
						<h4>OUR SERVICELIST</h4>
					</div>
					<ul class="widget-area service-list">
						<li><a href="#"><i class="fa fa-play-circle"></i><span>Hotel Stars Checking / Validation</span></a></li>
						<li><a href="#"><i class="fa fa-play-circle"></i><span>Vacation for wedding or holiday</span></a></li>
						<li><a href="#"><i class="fa fa-play-circle"></i><span>Rent a living room or a house</span></a></li>
						<li><a href="#"><i class="fa fa-play-circle"></i><span>Appartements for sale</span></a></li>
						<li><a href="#"><i class="fa fa-play-circle"></i><span>Buy your dream house and more</span></a></li>
					</ul>
				</div>
				<div class="col-md-3">
					<div class="widget-heading mrgb4x ">
						<h4>TWITTER FEED</h4>
					</div>
					<ul class="widget-area tweet">
						<li><a href="#"><i class="fa fa-twitter"></i><span>@envato  Creating a new theme for the real estate section</span> <span class="active-time"># 2 hours ago</span></a></li>
						<li><a href="#"><i class="fa fa-twitter"></i><span>@envato  We create awesome PSD templates for multi-pupose</span> <span class="active-time"># 8 hours ago</span></a></li>
					</ul>
				</div>
				<div class="col-md-3">
					<div class="widget-heading mrgb4x ">
						<h4>GET IN TOUCH WITH US</h4>
					</div>
					<ul class="widget-area contact clearfix">
						<li> <a href="#"><i class="icon-location10"></i><span>1700 Pennsylvania Ave NW, Washington DC</span></a></li>
					
						<li> <a href="#"><i class="fa fa-phone"></i><span>+55 555 555 5555</span></a></li>
						<li> <a href="#"><i class="icon-email4"></i><span>slimspace@email.com</span></a></li>
					</ul>
					<ul class="footer-social-media">
						<li><a href="#"><i class="fa fa-facebook"></i></a></li>
						<li><a href="#"><i class="fa fa-twitter"></i></a></li>
						<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
						<li><a href="#"><i class="fa fa-google"></i></a></li>
						<li><a href="#"><i class="icon-pinterest-p"></i></a></li>
						<li><a href="#"><i class="fa fa-instagram"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div class="lower-footer">
		<p>Made with<span><i class="fa fa-heart-o"></i></span>at BizHack DC </a> | Copyright Slimspace 2015</p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<div class="top-bar">
	<div class="container">
		<div class="left-bar">
			<ul class="social-media">
				<li class="facebook"><a href="#"><i class="fa fa-facebook"></i></a></li>
				<li class="twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
				<li class="google"><a href="#"><i class="fa fa-google"></i></a></li>
			</ul>
		</div>
		<div class="right-bar">
			<ul class="contact">
				<li><i class="fa fa-globe"></i></li>
        <li ><a href="/">Go Home</a></li>
			</ul>
			<ul class="mail">
				<li><i class="fa fa-envelope"></i></li>
				<li><span>Send Email</span></li>
        <li class="contact-info"><li><%= link_to "support@simspace.com", static_pages_contact_path %></li>
			</ul>
      
      <% if user_signed_in? %>
      
      <ul class="login">
        <li><i class="fa fa-mail-forward"></i></li>
        <li><%= link_to "View Spaces", spaces_path %></li>
        <li><i class="fa fa-sign-out"></i></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
			</ul>
      <% else %>
      
			<ul class="login">
				<li><i class="fa fa-sign-in"></i></li>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><i class="fa fa-user"></i></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
			</ul>
      
      <% end %>
		</div>
	</div>
</div>

app/views/layouts/_slider.html.erb
<div id="mainslider">
	<div class="slider">
		<div class="fullscreen-container">
			<div class="fullscreenbanner">
				<ul>
					<li data-transition="slide" data-slotamount="10"> <img class="img-responsive" alt="" src="http://res.cloudinary.com/dratccssz/image/upload/v1439095525/building-1489149_o81qfc.jpg"/>
						<div class="caption sfb" 
								data-x="center" 
								data-y="160" 
								data-speed="1000" 
								data-start="1000" 
								data-easing="easeOutExpo">
							<div class="slider-text clearfix">
								<div class="text-box">
									<h2>Luxurious Hotel Suite</h2>
									<p>Whether you’re looking to sell or let your home or want to buy or rent a</p>
									<p> home, we really are the people for you to come to.</p>
								</div>
								<div class="slider-button">
                  <% if user_signed_in? %>
                  <div class="view-btn"> <%= link_to "VIEW SPACES", spaces_path %></div>
                  <% else %>
                  <div class="signup-btn"><%= link_to "SIGN UP NOW", new_user_registration_path %> </div>
                  <% end %>
								</div>
							</div>
						</div>
					</li>
					<li data-transition="slide" data-slotamount="10"> <img class="img-responsive" alt="" src="http://res.cloudinary.com/dratccssz/image/upload/v1439095525/wireless-home-office-1240115_mxfeku.jpg"/>
						<div class="caption sfb" 
								data-x="center" 
								data-y="center" 
								data-speed="1000" 
								data-start="1000" 
								data-easing="easeOutExpo">
							<div class="slider-text clearfix">
								<div class="text-box">
									<h2>Luxurious Hotel Suite</h2>
									<p>Whether you’re looking to sell or let your home or want to buy or rent a</p>
									<p> home, we really are the people for you to come to.</p>
								</div>
								<div class="slider-button">
									<div class="view-btn"> <a href="">VIEW DETAILS</a> </div>
									<div class="signup-btn"> <a href="#">SIGNUP NOW</a> </div>
								</div>
							</div>
						</div>
					</li>
					<li data-transition="slide" data-slotamount="10"> <img class="img-responsive" alt="" src="http://res.cloudinary.com/dratccssz/image/upload/v1439095523/business-building-1484729_q3hu4x.jpg"/>
						<div class="caption sfb" 
								data-x="center" 
								data-y="center" 
								data-speed="1000" 
								data-start="1000" 
								data-easing="easeOutExpo">
							<div class="slider-text clearfix">
								<div class="text-box">
									<h2>Luxurious Hotel Suite</h2>
									<p>Whether you’re looking to sell or let your home or want to buy or rent a</p>
									<p> home, we really are the people for you to come to.</p>
								</div>
								<div class="slider-button">
									<div class="view-btn"> <a href="">VIEW DETAILS</a> </div>
									<div class="signup-btn"> <a href="#">SIGNUP NOW</a> </div>
								</div>
							</div>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SlimSpace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <!-- Latest compiled and minified JavaScript -->
   
  
  <%= csrf_meta_tags %>
  
</head>
<body>
  
  <%= render 'layouts/header' %>

  <%if @page=="index" %>
   <%= render 'layouts/slider' %>  
  <% end %>
  
   <div class="container">  
  <% flash.each do |name, msg| %>
           <% if msg.is_a?(String) %>
           <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable" > 
           <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
           <%= content_tag :div, msg, :id => "flash_#{name}" %>
       </div>
       
     <% end %>
    <% end %>

  
  <%= yield %>     
  </div>
  <%= render 'layouts/footer' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>

app/views/spaces/_errors.html.erb
<% if @space.errors.any? %>
  <div class="errors">
    <h3>
      <%= pluralize(@space.errors.count, 'error') %>
      prohibited this space from being saved:
    </h3>
    <ul>
      <% @space.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/spaces/_form.html.erb
<div class="col-md-6 col-md-offset-3">

<h2>Post a Space</h2>

<%= form_for @space do |f| %>
  <%= render 'errors' %>

  <div class="form-group">
    <%= f.text_field :name, placeholder: 'Name' , class:"form-control"%>
  </div>

  <div class="form-group">
    <%= f.text_field :address, placeholder: 'Address', class:"form-control"%>
  </div>

  <div class="form-group">
    <%= f.text_field :address, placeholder: 'Address', class:"form-control"%>
  </div>

  <div class="form-group">
  <%= f.text_field :city, placeholder: 'City', class:"form-control"%>
    
  </div>
  
   <div class="form-group">
  <%= f.text_field :state, placeholder: 'State', class:"form-control"%>
    
  </div>
  
   <div class="form-group">
  <%= f.text_field :description, placeholder: 'description', class:"form-control"%>
    
  </div>
  
  
   <div class="form-group">
<%= f.text_field :number_of_seats, placeholder: 'price', class:"form-control"%>
    
  </div>
  
   <div class="form-group">
   <%= f.file_field :image, class:"form-control" %>
    
  </div>
  
  <div class="form-group">
   <%= f.file_field :image, class:"form-control" %>
    
  </div>
  <div class="form-group">
    <%= f.submit 'Submit', class:"btn btn-primary btn-lg"%>
  </div>
  
<% end %>

</div>

app/views/spaces/edit.html.erb
<%= render 'form' %>

app/views/spaces/index.html.erb
<section class="border-top">
	<div class="container">
		<div class="page-title mrgb5x mrgt6x clearfix">
			<h4 class="page-name">properties list</h4>
			<div class="tag-bar"> <a href="#"><span>Prime production spaces</span></a> </div>
			<ul class="breadcrumb">
				<li><a href="/">Home</a></li>
				<li class="active"><%= link_to 'New Space', new_space_path %></li>
			</ul>
		</div>
	</div>
</section>

<section>
	<div class="container">
		<div class="property-filter clearfix">
	
			<div class="row">
				<ul class="filter-list clearfix">
          <% @spaces.each do |space| %>
					<li class="mix sale col-md-3 col-sm-4 mrgb5x" data-price="5">
						<div class="property-box animated out" data-delay="0" data-animation="fadeInUp">
              <div class="appartment-img"><%= link_to cl_image_tag(space.image_url(:mini)), space %>
							</div>
							<div class="property-text">
								<div class="appartment-name">
									<h4><%= space.name %></h4>
                  <p><%= space.city %>, <%= space.state %></p>
								</div>
								<div class="property-price">
                  <h1><span><sup>$</sup><%= space.price %></span></h1>
								</div>
								
							</div>
						</div>
					</li>
          <% end %>
				</ul>
			</div>
		</div>
	</div>
</section>

      

				

app/views/spaces/new.html.erb
<%= render 'form' %>

app/views/spaces/show.html.erb
<section class="border-top">
	<div class="container">
		<div class="page-title mrgb6x mrgt6x clearfix">
			<h4 class="page-name"><%= @space.city %></h4>
      <div class="tag-bar"> <a href="#"><span><%= @space.state %></span></a> </div>
			<ul class="breadcrumb">
				<li><a href="#">Pages</a></li>
				<li class="active"><a href="#">Property Single</a></li>
			</ul>
		</div>
	</div>
</section>
<section>
	<div class="container">
		<div class="property-single">
			<div class="col-md-6 no-padding col-sm-8 animated out" data-delay="0" data-animation="fadeInUp">
        <div class="property-single-img"><%= cl_image_tag(@space.image_url(:display)) %>
					<div class="image-detail">
						<h5 class="place-name"><%= @space.name %></h5>
            <div class="place-price"><span><%= @space.price %><sup>/week</sup></span></div>
					</div>
				</div>
			</div>
			<div class="col-md-6 col-sm-4 animated out" data-delay="0" data-animation="fadeInUp">
				<div class="property-heading property-info">
					<h4><span><%= @space.name %></span></h4>
					<p><%= @space.description %></p>
          <div class="booking-btn"><%= link_to "BOOK IT NOW", new_space_booking_path(@space), class:"book-it" %></div>
				</div>
        <div class="col-md-6 no-padding col-sm-6 animated out" data-delay="0" data-animation="fadeInUp">

			</div>
			</div>
		</div>
    
	</div>

</section>
<br><br>
  <% @space.bookings.each do |b| %>  
          <div class="alert alert-info" role="alert"> <i class="fa fa-info-circle"></i> <a href="#" class="alert-link">Current Booking:</a> <%= b.start_time.strftime("%b/%d/%Y")  %> at <%= b.start_time.strftime("%I:%M%p")  %> for <%= b.length %> hours</div>
          
       <% end %>

app/views/static_page/about.html.erb
<% @page="index" %>
<section>
	<div class="container" >
		<div class="featured-properties animated out" data-delay="0" data-animation="fadeInUp">
			<div class="section-heading mrgt7x mrgb7x">
				<h3><span>OUR FEATURED PROPERTIES</span></h3>
			</div>
      <% @spaces.each_slice(3) do |space_group| %>
			<div class="section-detail">
         <% space_group.each do |space| %>
				    <div class="col-md-4 col-sm-6 animated out" data-delay="0" data-animation="fadeInUp">
					<div class="property-box border-hover">
            <div class="appartment-img"><%= cl_image_tag(space.image_url(:thumbnail)) %>
              <div class="detail-btn"> <%= link_to 'More Detail', space, class:"more-detail" %> </div>
						</div>
						<div class="property-text">
							<div class="appartment-name">
								<h4><%= space.name %></h4>
							</div>
							<div class="property-price">
                <h1><span><sup>$</sup><%= space.price %></span></h1>
							</div>
							<ul class="appartment-detail">
                <li><%= space.number_of_seats %> seats in this space</li>
        <%= link_to 'Edit', edit_space_path(space) %>
        <%= link_to 'Destroy', space, method: :delete, data: { confirm: 'Are you sure?' } %>
              </ul>
						</div>
					</div>
				</div>
         <% end %>
			</div>
     <% end %>
		</div>
	</div>
</section>

app/views/static_page/contact.html.erb
<h1>Contact Us </h1>